### ISSUE TITLE
Creating a flutter app leads to invalid arguments error.

### ISSUE THREAD

**Issue by SomeCodingUser** [Pythagora-io/gpt-pilot#391] opened 2023-12-22 10:05 UTC
Hi,
I tried to create a flutter app, but the pilot always runs into the following error
```---------- GPT PILOT EXITING WITH ERROR ----------

Traceback (most recent call last):

File "c:\Users\Jo\Downloads\gpt-pilot\pilot\main.py", line 77, in <module> project.start()

File "c:\Users\Jo\Downloads\gpt-pilot\pilot\helpers\Project.py", line 90, in start self.project_manager.get_project_description()

File "c:\Users\Jo\Downloads\gpt-pilot\pilot\helpers\agents\ProductOwner.py", line 63, in get_project_description high_level_summary = self.generate_project_summary(high_level_messages)

File "c:\Users\Jo\Downloads\gpt-pilot\pilot\helpers\agents\ProductOwner.py", line 89, in generate_project_summary return convo_project_description.send_message('utils/summary.prompt',

File "c:\Users\Jo\Downloads\gpt-pilot\pilot\helpers\AgentConvo.py", line 85, in send_message self.replace_files()

File "c:\Users\Jo\Downloads\gpt-pilot\pilot\helpers\AgentConvo.py", line 188, in replace_files files = self.agent.project.get_all_coded_files()

File "c:\Users\Jo\Downloads\gpt-pilot\pilot\helpers\Project.py", line 199, in get_all_coded_files files = self.get_files([file.path + '/' + file.name for file in files])

File "c:\Users\Jo\Downloads\gpt-pilot\pilot\helpers\Project.py", line 227, in get_files file_data = get_file_contents(full_path, self.root_path)

File "c:\Users\Jo\Downloads\gpt-pilot\pilot\helpers\files.py", line 55, in get_file_contents file_content = open(path, "r", encoding="utf-8").read()

OSError: [Errno 22] Invalid argument: 'c:\Users\Jo\Downloads\gpt-pilot\workspace\reckless-drivin\reckless_drivin\.dart_tool\package_config_subset\'

--------------------------------------------------
```

The file package_config_subset contains the stuff like this:

```async
2.18
file:///C:/Users/Jo/AppData/Local/Pub/Cache/hosted/pub.dev/async-2.11.0/
file:///C:/Users/Jo/AppData/Local/Pub/Cache/hosted/pub.dev/async-2.11.0/lib/
boolean_selector
2.17
file:///C:/Users/Jo/AppData/Local/Pub/Cache/hosted/pub.dev/boolean_selector-2.1.1/
file:///C:/Users/Jo/AppData/Local/Pub/Cache/hosted/pub.dev/boolean_selector-2.1.1/lib/
characters
...
```

I'm not exactly sure how to debug from here. Please let me know which files you need in order to investigate the problem. I'm also happy to debug it myself with a little guidance.

**Comment by senko** [comment] 2023-12-23 19:20
This sounds like it might be the same underlying issue like #395, due to the presence of dot (`.`) in the directory name.

**Comment by senko** [comment] 2023-12-28 15:38
Closing as duplicate of #395

**Closed by senko** 2023-12-28 15:38 UTC
