### ISSUE TITLE
Overwriting issue

### ISSUE THREAD

**Issue by dsitnik** [Pythagora-io/gpt-pilot#392] opened 2023-12-22 14:33 UTC
When typed "n", gpt-pilot still overwrites all the data until the step. 
![image](https://github.com/Pythagora-io/gpt-pilot/assets/13439539/5f7d777c-7438-45ec-bc99-3aa398770654)

**Comment by senko** [comment] 2023-12-26 16:47
Marking this as duplicate of #425 because the other issue has more information.

**Closed by senko** 2023-12-26 16:47 UTC
Labels: bug
