### ISSUE TITLE
VSCODE APP IS VERY BUGGY

### ISSUE THREAD

**Issue by RFARREY** [Pythagora-io/gpt-pilot#399] opened 2023-12-22 22:54 UTC
I've tried everything I can't get it to work on vscode. It works well in my terminal. 
![Screenshot 2023-12-23 005124](https://github.com/Pythagora-io/gpt-pilot/assets/45320379/cf9a3715-a6f9-4d04-9e1b-3f163b8148fc)
![Screenshot 2023-12-23 005106](https://github.com/Pythagora-io/gpt-pilot/assets/45320379/248fcf8c-ecce-4dbd-89da-f99d1a5b09ac)

**Comment by senko** [comment] 2023-12-23 18:56
Duplicate of #387

**Closed by senko** 2023-12-23 18:56 UTC
