### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by omniscient24** [Pythagora-io/gpt-pilot#414] opened 2023-12-24 02:09 UTC
When building the code on Mac Sonoma 14.2.1 (MacBook Pro) in VS Code 1.8.1.0, receiving a NotADirectoryError: [Errno 20] Not a directory on the '/pre-commit/' file.

**Comment by jeremyjs** [comment] 2023-12-24 04:59
Got this one: 

```
(pilot-env) (base) jeremy@As-Macbook-Pro pilot % python main.py app_id=29e722ff-cc08-4965-a8a9-c2abc42f971c


------------------ LOADING PROJECT ----------------------
BitBasel (app_id=29e722ff-cc08-4965-a8a9-c2abc42f971c)
--------------------------------------------------------------

✅  Project_description
✅  Architecture
✅  Environment_setup
✅  Development_planning
🚀 Now for the actual development...

Implementing task #1:  Initialize Next.js application with Tailwind CSS configuration and create a shared layout component that includes a header and a footer that are present on all pages.

---------- GPT PILOT EXITING WITH ERROR ----------
Traceback (most recent call last):
  File "/Users/jeremy/Development/hyper-modern/gpt-pilot/pilot/main.py", line 77, in <module>
    project.start()
  File "/Users/jeremy/Development/hyper-modern/gpt-pilot/pilot/helpers/Project.py", line 141, in start
    self.developer.start_coding()
  File "/Users/jeremy/Development/hyper-modern/gpt-pilot/pilot/helpers/agents/Developer.py", line 66, in start_coding
    self.implement_task(i, dev_task)
  File "/Users/jeremy/Development/hyper-modern/gpt-pilot/pilot/helpers/agents/Developer.py", line 99, in implement_task
    "files": self.project.get_all_coded_files(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremy/Development/hyper-modern/gpt-pilot/pilot/helpers/Project.py", line 199, in get_all_coded_files
    files = self.get_files([file.path + '/' + file.name for file in files])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremy/Development/hyper-modern/gpt-pilot/pilot/helpers/Project.py", line 227, in get_files
    file_data = get_file_contents(full_path, self.root_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremy/Development/hyper-modern/gpt-pilot/pilot/helpers/files.py", line 55, in get_file_contents
    file_content = open(path, "r", encoding="utf-8").read()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/Users/jeremy/Development/hyper-modern/gpt-pilot/workspace/BitBasel/bitbasel-app/.next/trace/'
--------------------------------------------------
? We would appreciate if you let us store your initial app prompt. If you are OK with that, please just press ENTER
```

**Comment by senko** [comment] 2023-12-24 08:58
Duplicate of #395

**Closed by senko** 2023-12-24 08:58 UTC
