### ISSUE TITLE
[Bug]: read gradlew as a Directory

### ISSUE THREAD

**Issue by warzx** [Pythagora-io/gpt-pilot#444] opened 2023-12-27 15:52 UTC
### Version

VisualStudio Code extension

### Operating System

MacOS

### What happened?

When generating the files for my flutter project, I got this error (appologies for the screenshot, I cannot copy paste the error log):
<img width="528" alt="image" src="https://github.com/Pythagora-io/gpt-pilot/assets/69043715/37c20541-c98c-482a-86a4-373ae4b2373e">
I think this is because of the script reads gradlew as a Directory, but gradlew is not a directory, it is a wrapper for the android gradle, here is the file:
<img width="1601" alt="image" src="https://github.com/Pythagora-io/gpt-pilot/assets/69043715/01ae6b18-e908-4ea4-ad29-42d2bdbfca2a">

**Comment by senko** [comment] 2023-12-28 15:38
Duplicate of #395

**Closed** 2023-12-28 15:49 UTC
Labels: bug
