### ISSUE TITLE
[Bug]: Wrong `cd` command to enter the project directory

### ISSUE THREAD

**Issue by Michal-Mikolas** [Pythagora-io/gpt-pilot#470] opened 2023-12-30 13:21 UTC
### Version

Command-line (Python) version

### Operating System

Windows 10

### What happened?

When I prompt GPTP to create "Hello World" app (using PHP and Laravel framework), it creates this folder structure: 

```
workspace
└ helloworld
  └ helloworld
  └ tests
```

Later it want's to execute command `cd helloworld` which is wrong, because the real project is in `helloworld/helloworld` folder. 

```
--------- EXECUTE COMMAND ----------
Can I execute the command: `cd helloworld` with 5000ms timeout?

? If yes, just press ENTER. Otherwise, type "no" but it will be processed as successfully executed.
```

So later, when it tries to run `php artisan serve` to start the web server, it obviously ends up with an error (becouse `artisan` file is in `workspace/helloworld/helloworld` folder, not in `workspace/helloworld` folder): 

![bsM1O9220D](https://github.com/Pythagora-io/gpt-pilot/assets/900316/875f3c10-ee49-4ee3-b7fb-9b312bc8f12e)

**Comment by Michal-Mikolas** [comment] 2023-12-30 13:22
If you want to test the exact same prompt like me: 

`It is website written in PHP in Laravel framework. And it is just "Hello world" page. On the web page there is just homepage with "Hello world" headline.`

**Comment by senko** [comment] 2024-01-02 13:35
Looks like it might be the same error as https://github.com/Pythagora-io/gpt-pilot/issues/440

**Comment by senko** [comment] 2024-01-10 18:44
Closing as duplicate of #440

**Closed by senko** 2024-01-10 18:44 UTC
Labels: bug
