### ISSUE TITLE
[Bug]: Wont finish project, loop

### ISSUE THREAD

**Issue by Bengan1** [Pythagora-io/gpt-pilot#504] opened 2024-01-07 11:01 UTC
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

After a while of developling, I had it happen two or tree times. One at 105 steps and another one at 207 steps. Gpt pilot just stop producing anything and asks: 
`We would appriciate if you let us store your inital app promt. If you are OK with that please just press 
 ENTER
`

After that VScode jsut quits. 

When I start it up after the shutdown it goes to the last lines again and crashes.

**Comment by senko** [comment] 2024-01-07 13:32
Thanks for reporting this.

Could you take a screenshot or paste output from GPT right *before* the "can we store your output?" message?

This should give us a clue to the root cause of the problem.

**Comment by Bengan1** [comment] 2024-01-07 14:20
![Screenshot 2024-01-07 151943](https://github.com/Pythagora-io/gpt-pilot/assets/36185815/4dac94b2-7297-4e8a-84dd-857f645190bc)

**Comment by Bengan1** [comment] 2024-01-10 07:10
Giot it again... So my project is about 60% done and this comes up.

`Dev step 528

---------- GPT PILOT EXITING WITH ERROR ----------

Traceback (most recent call last):

File "c:\GPTPilot\gpt-pilot\pilot\main.py", line 77, in <module> project.start()

File "c:\GPTPilot\gpt-pilot\pilot\helpers\Project.py", line 141, in start self.developer.start_coding()

File "c:\GPTPilot\gpt-pilot\pilot\helpers\agents\Developer.py", line 66, in start_coding self.implement_task(i, dev_task)

File "c:\GPTPilot\gpt-pilot\pilot\helpers\agents\Developer.py", line 113, in implement_task result = self.execute_task(convo_dev_task, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\GPTPilot\gpt-pilot\pilot\helpers\agents\Developer.py", line 451, in execute_task return self.task_postprocessing(convo, development_task, continue_development, result, function_uuid) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\GPTPilot\gpt-pilot\pilot\helpers\agents\Developer.py", line 313, in task_postprocessing return self.continue_development(convo, last_branch_name, continue_description, development_task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\GPTPilot\gpt-pilot\pilot\helpers\agents\Developer.py", line 493, in continue_development iteration_description = iteration_convo.send_message('development/iteration.prompt', { ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "c:\GPTPilot\gpt-pilot\pilot\helpers\AgentConvo.py", line 112, in send_message self.log_message(message_content)

File "c:\GPTPilot\gpt-pilot\pilot\helpers\AgentConvo.py", line 247, in log_message print(f"\n{content}\n", type='local')

File "c:\GPTPilot\gpt-pilot\pilot\utils\custom_print.py", line 16, in print_to_external_process local_print(*args, **kwargs)

File "c:\GPTPilot\gpt-pilot\pilot\utils\custom_print.py", line 33, in local_print built_in_print(message, **kwargs)

File "c:\GPTPilot\gpt-pilot\pilot-env\Lib\site-packages\colorama\ansitowin32.py", line 47, in write self.__convertor.write(text)

File "c:\GPTPilot\gpt-pilot\pilot-env\Lib\site-packages\colorama\ansitowin32.py", line 177, in write self.write_and_convert(text)

File "c:\GPTPilot\gpt-pilot\pilot-env\Lib\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert self.write_plain_text(text, cursor, len(text))

File "c:\GPTPilot\gpt-pilot\pilot-env\Lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text self.wrapped.write(text[start:end])

File "C:\Users\borgj\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode return codecs.charmap_encode(input,self.errors,encoding_table)[0] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

UnicodeEncodeError: 'charmap' codec can't encode characters in position 3381-3382: character maps to <undefined>

![Screenshot 2024-01-10 070839](https://github.com/Pythagora-io/gpt-pilot/assets/36185815/3fae9dae-ab3a-4d03-987e-d380850888bf)
`

**Comment by senko** [comment] 2024-01-10 07:42
@Bengan1 can you try the workaround from #509 and let me know (in that issue comments) if that worked for you?

Closing as duplicate of #509

**Closed by senko** 2024-01-10 07:42 UTC
Labels: bug
