### ISSUE TITLE
[Bug]: Can't get early access

### ISSUE THREAD

**Issue by oceanroi** [Pythagora-io/gpt-pilot#1109] opened 2024-10-08 18:52 UTC
### Version

VisualStudio Code extension

### Operating System

Ubuntu Linux

### What happened?

still waiting in the waiting list can you add me please

**Comment by oceanroi** [comment] 2024-10-08 18:53
my email is roitmaster@gmail.com

**Comment by Plavixal2023** [comment] 2024-10-16 05:29
I got access but when the app came up it told me I had a bad branch.   I fixed the branch and reloaded nodejs and mongodb and python but now the original app has disappeared from my open VSS code window and I have tried to get it back but I can't.   A little help here please.  I paid for the Pythagora pro plan

**Comment by roitmaster** [comment] 2024-10-19 21:49
i found the vs extension is GPT-pilot and then you can reset the password

**Comment by Asifali2o** [comment] 2024-10-30 17:39
Thanks for the valuable post! I've been following along, and it's great to see the enthusiasm for this extension. While you're waiting for the list, you might want to check out [Mattress cleaning company](https://mattressclean.ch/) based in Switzerland. They specialize in eco-friendly mattress cleaning solutions, which could come in handy for keeping your workspace fresh and dust-free while coding. Keep up the good work!

**Comment by westonludeke** [comment] 2024-11-18 21:47
Closing this since it's not a bug. If anyone else needs v1 access, you can send us an email to check on the status of your Pythagora v1 invite: support@pythagora.ai

**Closed by westonludeke** 2024-11-18 21:47 UTC
Labels: bug
