### ISSUE TITLE
There is an issue with the helpers/files.py script when dealing with files that do have extension.

### ISSUE THREAD

**Issue by AndreVianna** [Pythagora-io/gpt-pilot#418] opened 2023-12-24 15:38 UTC
I am running a few experiments with the VS Code extension and the script always stops at the same place.

This is the code:
    try:
        # Assume it's a text file using UTF-8 encoding
        file_content = open(path, "r", encoding="utf-8").read()
    except UnicodeDecodeError:
        # If that fails, we'll treat it as a binary file
        file_content = open(path, "rb").read()
    except FileNotFoundError:
        raise ValueError(f"File not found: {path}")
        
These are the messages I get in VS Code:
OSError [Errno 22] invalid argument '{path of a file ending with "\"}'

Some of the files that give that error: "Dockerfile", "LICENSE"
Here is the full strings of the error: 
Test 1 uses Docker
OSError [Errno 22] invalid argument 'c:\gpt-pilot\workspace\test1\Dockerfile\'

Test 2 do not uses Docker but has a reference on the project to the LICENSE file from GitHub
OSError [Errno 22] invalid argument 'c:\gpt-pilot\workspace\test2\LICENSE\'

I am running on a Windows 11 machine, with Python 3.12 installed

UPDATE: In the case of Test 2 if I add a ".txt" at the end of the LICENSE file everything works. But I can't do the same with the Dockefile becase if I do the Docker commands will fail..

**Comment by senko** [comment] 2023-12-24 15:45
Duplicate of #395

**Closed by senko** 2023-12-24 15:45 UTC
Labels: bug
